info:
  _postman_id: e57268ce-b3ae-4116-a827-8909c8cb0a49
  name: banking_app
  schema: https://schema.getpostman.com/json/collection/v2.1.0/collection.json
  description: ""
item:
  - name: register
    request:
      method: POST
      url:
        raw: https://banking-app-fis7hiuba-isaac-svg.vercel.app/api-docs/auth/register
        path:
          - auth
          - register
        host:
          - localhost
        port: "4000"
      body:
        mode: raw
        options:
          raw:
            language: json
        raw: |-
          {
            "first_name": "emmanuel",
            "last_name": "sakyi",
            "dob": "09-09-09",
            "phone": "0506851863",
            "email": "emanuelsakyi226@gmail.com",
            "address": "New York",
            "ghana_card_number": "GHA-2345-334",
            "password": "123456"
          }
  - name: login
    request:
      method: POST
      url:
        raw: localhost:4000/auth/login
        path:
          - auth
          - login
        host:
          - localhost
        port: "4000"
      body:
        mode: raw
        options:
          raw:
            language: json
        raw: |-
          {
            "first_name": "isaac",
            "last_name": "sakyi",
            "email": "isaacsakyi12321@gmail.com",
            "password": "123456"
          }
  - name: logout
    request:
      method: POST
      url:
        raw: localhost:4000/auth/logout
        path:
          - auth
          - logout
        host:
          - localhost
        port: "4000"
  - name: profile
    request:
      method: GET
      url:
        raw: localhost:4000/auth/profile
        path:
          - auth
          - profile
        host:
          - localhost
        port: "4000"
  - name: checkbalance
    request:
      method: GET
      url:
        raw: localhost:4000/transaction/checkbalance
        path:
          - transaction
          - checkbalance
        host:
          - localhost
        port: "4000"
  - name: getallcustomers
    request:
      method: GET
      url:
        raw: localhost:4000/sudo/allcustomers
        path:
          - sudo
          - allcustomers
        host:
          - localhost
        port: "4000"
  - name: transfer
    request:
      method: POST
      url:
        raw: localhost:4000/transaction/transfer
        path:
          - transaction
          - transfer
        host:
          - localhost
        port: "4000"
      body:
        mode: raw
        options:
          raw:
            language: json
        raw: |-
          {
            "from_account_number": "1402222550431738",
            "to_account_number": "1402223962123316",
            "amount": "91"
          }
  - name: getprofile
    request:
      method: GET
      url:
        raw: localhost:4000/get/profile
        path:
          - get
          - profile
        host:
          - localhost
        port: "4000"
  - name: getaccountnumber
    request:
      method: GET
      url:
        raw: localhost:4000/get/account_number
        path:
          - get
          - account_number
        host:
          - localhost
        port: "4000"
      body:
        mode: raw
        options:
          raw:
            language: json
        raw: |-
          {
            "account_number": "1402222550431738"
          }
